version: '3'
services:
#Nginx Service
 webserver:
  image: nginx:latest
  container_name: e-bot7-webserver
  restart: unless-stopped
  tty: true
  ports:
    - "80:80"
  volumes:
   - /opt/e-bot7/index-page/:/usr/share/nginx/html
   - /opt/e-bot7/conf.d/:/etc/nginx/conf.d/
#Notification service
 notifiebserver:
   build: .
   container_name: e-bot7-notifiebserver
   restart: unless-stopped
   ports:
      - "465:465"
   volumes: 
    - shared_volume:/opt/
volumes:
 shared_volume:

